#!/bin/bash
#PBS -S /bin/bash
#PBS -r n
#PBS -l procs=8
#PBS -l walltime=01:00:00
#PBS -l pmem=600m
#PBS -m bea
#PBS -M markjboots@gmail.com; jesaja.weintritt@stud.eah-jena.de
 
cd $PBS_O_WORKDIR
echo "Current working directory is `pwd`"

echo "Node file: $PBS_NODEFILE :"
echo "---------------------"
cat $PBS_NODEFILE
echo "---------------------"

NUM_PROCS=`/bin/awk 'END {print NR}' $PBS_NODEFILE`
echo "Running on $NUM_PROCS processors."

echo "prog started at: `date`"

REPS=30
for ((i=1;i<=REPS;i++))
do
  DATE=`date --rfc-3339=ns`
  mpiexec -n ${NUM_PROCS} ./pegMPI --computeTE --mode constantIncidence --min 100 --max 131 --increment 1 --incidenceAngle 88 --outputFile "output/${DATE}_rep${i}.txt" --progressFile "output/progress${DATE}_rep${i}.txt" --gratingType blazed --gratingPeriod 1 --gratingMaterial Au --N 15 --gratingGeometry 2.5,30 --eV
done

echo "prog finished at: `date`"