# Library paths: Uncomment as required:
#####################
INCLUDEPATH += /usr/include/eigen3
#LIBPATH=/home/user/lib

CC=mpic++
CFLAGS=-c -g -Wall -fopenmp $(if $(INCLUDEPATH),-I$(INCLUDEPATH))
LDFLAGS=-fopenmp $(if $(LIBPATH),-L$(LIBPATH))
SOURCES=mainSerial.cpp mainMPI.cpp PEG.cpp TESolver.cpp mainSupport.cpp
OBJECTS=$(SOURCES:.cpp=.o)

all: $(SOURCES) pegSerial pegMPI

pegSerial: mainSerial.o mainSupport.o PEG.o TESolver.o
	$(CC) $(LDFLAGS) mainSerial.o mainSupport.o PEG.o TESolver.o -o ../$@

pegMPI: mainMPI.o mainSupport.o PEG.o TESolver.o
	$(CC) $(LDFLAGS) mainMPI.o mainSupport.o PEG.o TESolver.o -o ../$@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@