# Library paths: Uncomment as required:
#####################
#INCLUDEPATH=/home/user/include
#LIBPATH=/home/user/lib

CC=mpic++
CFLAGS=-c -g -Wall -fopenmp
LDFLAGS=-fopenmp -lgsl -lgslcblas
SOURCES=mainSerial.cpp mainMPI.cpp PEG.cpp TESolver.cpp mainSupport.cpp
OBJECTS=$(SOURCES:.cpp=.o)

all: $(SOURCES) pegSerial pegMPI

pegSerial: mainSerial.o mainSupport.o PEG.o TESolver.o
	$(CC) $(LDFLAGS) mainSerial.o mainSupport.o PEG.o TESolver.o -o ../$@

pegMPI: mainMPI.o mainSupport.o PEG.o TESolver.o
	$(CC) $(LDFLAGS) mainMPI.o mainSupport.o PEG.o TESolver.o -o ../$@